# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - grp1-gitgud-cicd

on:
  push:
    branches:
      - main
  workflow_dispatch:

env: 
  DATABASE_URL: ${{ vars.DATABASE_URL}}
  PORT: ${{ vars.PORT}}  
  JWT_SECRET_KEY: ${{ vars.JWT_SECRET_KEY}} 
  JWT_EXPIRES_IN: ${{ vars.JWT_EXPIRES_IN}} 
  JWT_ALGORITHM: ${{ vars.JWT_ALGORITHM}} 

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: npm install project dependencies
        run: npm install
        
      - name: Install playwright browsers
        run: npx playwright install

      - name: build, and test
        run: |
          npm run build --if-present
          npm run test --if-present

      - name: Zip artifact for deployment
        run: zip release.zip ./* -r

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_8A84FDDEDDA84E76A8C8057591E5CE74 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_D90F6FBDF80147B793E6F28EC282EB7F }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_82CE3A6CA3E349CDBE4B379F68B8F8BD }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'grp1-gitgud-cicd'
          slot-name: 'Production'
          package: .
          
